project:
  type: website

website:
  title: "vc-2024"
  open-graph: true
  favicon: favicon-16x16.png
  navbar:
    left:
      - href: index.qmd
        text: Blog
      - about.qmd
    logo: fff_logo_50pct.png
    background: dark
  page-footer: 
    left: "FFF VÃ¥rcup 2024"
    right: "Sportchefen FFF"
    border: true
    background: light

format:
  html:
    theme: cerulean
    css: styles.css
    toc: true

editor: visual

